[tool.poetry]
name = "bpl"
version = "0.1.0"
description = ""
authors = ["Angus Williams <anguswilliams91@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.7.1,<4.0"
numpyro = "^0.6.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^22.1.0"
isort = "^5.8.0"
pytest-cov = "^2.11.1"
pylint = "^2.7.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
