[project]
name = "bpl-next"
version = "0.5.0"
description = ""
authors = [{ name = "Angus Williams", email = "anguswilliams91@gmail.com" }]
requires-python = ">=3.10,<4"
dependencies = [
    "numpy>=2.2.6",
    "numpyro>=0.19.0",
    "pip>=26.2.1",
    "scipy>=1.15.3",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "pytest-cov>=7.0.0",
    "ruff>=0.13.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 88

[tool.ruff.format]
docstring-code-format = true  # code snippets in docstrings will be formatted

[tool.ruff.lint]
select = [
  "E", "F", "W", # flake8
  "B",           # flake8-bugbear
  "I",           # isort
  "ARG",         # flake8-unused-arguments
  "C4",          # flake8-comprehensions
  "EM",          # flake8-errmsg
  "ICN",         # flake8-import-conventions
  "ISC",         # flake8-implicit-str-concat
  "G",           # flake8-logging-format
  "PGH",         # pygrep-hooks
  "PIE",         # flake8-pie
  "PL",          # pylint
  "PT",          # flake8-pytest-style
  "RET",         # flake8-return
  "RUF",         # Ruff-specific
  "SIM",         # flake8-simplify
  "UP",          # pyupgrade
  "YTT",         # flake8-2020
  "EXE",         # flake8-executable
]
ignore = [
  "PLR",    # Design related pylint codes
  "ISC001", # Conflicts with formatter
]
flake8-unused-arguments.ignore-variadic-names = true  # allow unused *args/**kwargs

[tool.ruff.lint.per-file-ignores]
"**/__init__.py" = [
	"F401",  # allow unused imports in __init__.py files
]
"**/tests/**" = [
	"B011",  # allow using assert statements in tests
	"ARG001"  # allow unused arguments in tests, e.g. for pytest fixtures
]
