name: Tests and linting
on: pull_request

jobs:
  tests:
    name: Run tests and linters
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: "Set up python ${{ matrix.python-version }}"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.2

      - name: Install Dependencies
        run: poetry install

      # FIXME: pylint set to fail under 9.5 only to temporarily work around warnings
      - name: Code Quality
        run: |
          poetry run black bpl --check
          poetry run isort bpl -c -v
          poetry run pylint --fail-under 9 bpl

      - name: Test with pytest
        run: poetry run pytest --cov .
